version: 1
accounts:
  - name: andresWallet
    coins: [54000000000000tkii]
genesis:
  chain_id: kiiventador
  app_state:
    staking:
      params:
        bond_denom: tkii
validators:
  - name: andresWallet
    bonded: 100000000000tkii
    app:
      pruning: "default"
    config:
      moniker: "andresValidator"
    client:
      output: "json"
